parameters:
#    bambuk_cms_post.example.class: BambukCms\PostBundle\Example
services:
    form.type.translatable:
      class: Ladela\PersonalTranslationsWidgetBundle\Form\Type\TranslatableFieldType
      arguments: [ @service_container ]
      tags:
       - { name: form.type, alias: translatable_field }             
    post.BambukCms.admin.post:
      class: BambukCms\PostBundle\Admin\PostAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: BambukCms, label: Статті }
      arguments: [null, BambukCms\PostBundle\Entity\Post, BambukCmsPostBundle:PostAdmin]
     