<?php

namespace BambukCms\PostBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
	public function getTranslatableFieldsTiele($id)
	{
		/*$translationMeta = $this->getClassMetadata();
	
		$qb = $this->_em->createQueryBuilder();
		$qb->select('trans.field')
		->from($translationMeta->rootEntityName, 'trans')
		->where('trans.objectClass = :entityClass')
		->groupBy('trans.field');
	
		$q = $qb->getQuery();
	
		$data = $q->execute(
				array('entityClass' => $className),
				Query::HYDRATE_ARRAY
		);*/
	
		return $id;
	}
}
