<?php

namespace BambukCms\PageBundle\Entity;
use Gedmo\Translatable\Translatable;
use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
	
	
}
